name: compound_calc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  functional_widget: ^0.10.2
  functional_widget_annotation: ^0.10.0
  signals: ^4.5.1
  tailwind:
    path: tailwind
  tailwind_standards: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  tailwind_cli: ^0.7.2

flutter:
  uses-material-design: true
